name: smart_overlay_menu
description: >
  A professional Flutter package providing customizable overlay menus with haptic feedback,
  automatic positioning, smooth animations, and programmatic control. Perfect for context menus and action overlays.
version: 1.0.3
homepage: https://github.com/sgruhier/smart_overlay_menu
repository: https://github.com/sgruhier/smart_overlay_menu
issue_tracker: https://github.com/sgruhier/smart_overlay_menu/issues
documentation: https://pub.dev/documentation/smart_overlay_menu/latest/

topics:
  - overlay
  - menu
  - context-menu
  - flutter-widget
  - ui-components

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
